### ISSUE TITLE
when() and always() are throwing "Error: convergent assertion encountered a async function or promise; since convergent assertions can run multiple times, you should avoid introducing side-effects inside of them"

### ISSUE THREAD

**Issue by jonnolen** [bigtestjs/convergence#25]
bigtest/convergence v 1.1.1

```
it('why does it say async function when there is no async function?!', always( () => {
   expect(0).to.not.equal(1);
}));
```

```
it('why does it say async function when there is no async function?!', always( () => {
   return 0 !== 1;
}));
```

**Comment by Robdel12** [comment]
Hmm, looks like something is going wrong here: https://github.com/bigtestjs/convergence/blob/0d17597ebe588db6d342aefada23fc3f108c183f/src/converge.js#L50-L57

Is that exact snippet that's throwing the error? 🤔

**Comment by jonnolen** [comment]
nevermind.  there was a conflict with bigtest/mocha and bigtest/convergence.  bigtest/mocha was wrapping all of the it assertions with a when by default which was then being passed an always block... which bigtest/mocha correctly detects as being an async method....

**Comment by Robdel12** [comment]
Gotcha! That makes sense. We saw some issues where `@bigtest/mocha` would subtly troll people because it requires a strict testing style. All effects in `beforeEach` and pure assertions in `its` 😊

So that's where that error came from. If you mix and match that style, what you did was totally valid outside of `@bigtest/mocha`. You could use a regular mocha setup and use `async/await` too.
